### ISSUE TITLE
gaze_at_pose heavy CPU usage

### ISSUE THREAD

**Issue by jayyoung** [strands-project/strands_hri#149]
I am not sure who is responsible for this package any more, but we notice that it's using anywhere between 60% and 90% CPU usage, but only 0.2% memory. Are there some efficiency improvements that can be made anywhere to curb this? 

@OMARI1988 @PDuckworth are the ones using it.

I notice the main bit of the script is wrapped in a 

````
while(ros::ok()) 
````
So maybe this is to blame?

**Comment by cdondrup** [comment]
Actually, [this line](https://github.com/strands-project/strands_hri/blob/hydro-devel/strands_gazing/src/gaze_at_pose/gaze_at_pose.cpp#L147) should prevent it from using too much cpu. Only if the transform fails it calls a continue that bypasses this sleep. Maybe just adding another `r.sleep()` before [this line](https://github.com/strands-project/strands_hri/blob/hydro-devel/strands_gazing/src/gaze_at_pose/gaze_at_pose.cpp#L120) might solve this issue? But then it should also print a warning all the time.

Otherwise, I never noticed any high CPU usage or would have an idea why that happens.

**Comment by hawesie** [comment]
Good call @cdondrup the logs have a lot of "msg: Failed transform: Quaternion malformed, magnitude: 0 should be 1.0"
